### ISSUE TITLE
Missing support for various elements

### ISSUE THREAD

**Issue by euphilein** [stephanstapel/OpenTrans.net#10]
Support for following tags seems to be missing:

- CONTROL_INFO
  - GENERATOR_INFO
- ORDER_INFO
  - CUSTOMER_ORDER_REFERENCE
    - ORDER_ID
  - ORDER_PARTIES_REFERENCE
    - bmecat:BUYER_IDREF
    - bmecat:SUPPLIER_IDREF
    - SHIPMENT_PARTIES_REFERENCE
  - bmecat:CURRENCY
  - PARTIAL_SHIPMENT_ALLOWED

- SHIPMENT_PARTIES_REFERENCE
  - DELIVERY_IDREF

- ORDER_ITEM
  - PRODUCT_FEATURES
    - FEATURE
      - bmecat:FNAME
      - bmecat:FVALUE
  - PRODUCT_PRICE_FIX
    - bmecat:PRICE_AMOUNT
    - bmecat:PRICE_QUANTITY

- ORDER
  - ORDER_SUMMARY 
    - TOTAL_ITEM_NUM
    - TOTAL_AMOUNT

**Comment by stephanstapel** [comment]
I'll take a look at this as soon as I can. In the meanwhile I'm happy to review pull requests.

**Comment by stephanstapel** [comment]
https://www.nuget.org/packages/OpenTrans.net/2.2.0
