### ISSUE TITLE
InvalidOperationException when saving to file

### ISSUE THREAD

**Issue by Schaussi** [stephanstapel/OpenTrans.net#2]
Hi,

I just tried your _createOrder() example method of file Application.cs.
Unfortunately, the Save() method results in an exception (message in German: "Token StartElement im Status Epilog würde in einem ungültigen XML-Dokument resultieren.").
An empty XML file is created.

This also happens when creating an order with minimal given items like only an order ID, and even with an empty order.

For me it seems like there is some invalid base XML tag created within the library.

It would be great if you could solve this error.

Thank you!

Edit: It happens in OrderWriter.cs; it cannot write the items ORDER_ITEM_LIST, ORDER_SUMMARY and TOTAL_ITEM_NUM.
Could maybe some none-existing URLs on top (xmlns, schemaLocation etc.) be the cause?

**Comment by stephanstapel** [comment]
fixed in https://github.com/stephanstapel/OpenTrans.net/commit/bdd8cc580d9fb6af3c6ce241d47b1c30cbcd8b01

**Comment by stephanstapel** [comment]
added new nuget package:
https://www.nuget.org/packages/OpenTrans.net/1.1.0
