### ISSUE TITLE
some elements are in the wrong position

### ISSUE THREAD

**Issue by PatrickSproll** [stephanstapel/OpenTrans.net#22]
according to specification
- CONTACT_DETAILS has to be between DEPARTMENT and STREET
- EMAILS has to be between URL and AUTHENTIFICATION
- PRODUCT_FEATURES has to be between PRODUCT_ID and PRODUCT_COMPONENTS

**Comment by PatrickSproll** [comment]
Can you please release a new version of NuGet with these changes?

**Comment by stephanstapel** [comment]
consider it done (tonight)

**Comment by stephanstapel** [comment]
done:
https://github.com/stephanstapel/OpenTrans.net/releases/tag/4.0.1
https://www.nuget.org/packages/OpenTrans.net/

**Comment by PatrickSproll** [comment]
Sorry, but I think it's not done
it seems that version 4.0.1 has the same behavior as version 4.0.0

**Comment by stephanstapel** [comment]
oh, sorry to hear that. I'll drop another package tonight. Can you please verify that your changes are present in the master branch?

**Comment by PatrickSproll** [comment]
yes, the changes are in the master branch

**Comment by stephanstapel** [comment]
I have re-packaged the library as 4.0.2 (plus adding some documentation). Can you verify that it is alright now?

**Comment by PatrickSproll** [comment]
Yes, everything is fine now, thanks

**Comment by stephanstapel** [comment]
I am glad that this is solved!
