### ISSUE TITLE
Issue when recipient is using XmlConvert.ToBoolean to parse boolean field

### ISSUE THREAD

**Issue by btastic** [stephanstapel/OpenTrans.net#29]
Hello Stephan,

first off, thanks for your work. It is a really easy to use API and the documents look good for us.

We noticed that you hardcoded `PARTIAL_SHIPMENT_ALLOWED` to `TRUE` or `FALSE` when creating the Order object: https://github.com/stephanstapel/OpenTrans.net/blob/5b8d02d0d7bcc89273dda38d1f609714ba13a569/OpenTrans.net/OrderWriter.cs#L91

However, we noticed that our receiver system seems to be using `XmlConvert.ToBoolean`, which apparently does not like the upper-case variant of `TRUE` or `FALSE`.

Since the openTRANS 2.1 document states, dtBoolean values are case-insensitive.

What is your view on changing it in your library, to make it seemingly more broadly compatible with other systems vs. keeping it upper-case, since it should not matter?

Thanks!

**Comment by stephanstapel** [comment]
Thanks for raising this issue.
Isn't that a problem on the receiver side which should be able to parse the boolean value in a case-insensitive manner?

**Comment by btastic** [comment]
Yes, of course. It would have been more convinient of course, to have it changed in the library. But thats why I was asking.

Thanks!
