### ISSUE TITLE
_translateCountry() additions

### ISSUE THREAD

**Issue by Schaussi** [stephanstapel/OpenTrans.net#3]
Hi,

not an urgent issue, but maybe you could add some more country codes to the _translateCountry method, e.g. at least "Austria / AT".

Thank you!

**Comment by stephanstapel** [comment]
fixed with https://github.com/stephanstapel/OpenTrans.net/commit/8da0c9def7a710475497ab1742609dce6951313e

**Comment by stephanstapel** [comment]
added new nuget package:
https://www.nuget.org/packages/OpenTrans.net/1.1.0
