### ISSUE TITLE
Quantity Codes are not complete

### ISSUE THREAD

**Issue by jmu-horaios** [stephanstapel/OpenTrans.net#31]
I noticed that the current package published on Nuget lists every existing unit of measurement and probably more, but the latest version on GitHub just lists a few codes. Did this reduction happen by mistake, or was there an intention?

Also, while I was searching for some codes I found [this website](https://resources.gs1us.org/GS1-US-Data-Hub-Help-Center/ArtMID/3451/ArticleID/116/Unit-of-Measure-Codes). It has a table of all codes with proper unit name and sometimes even a description. Maybe I can find some time to write a script for parsing the table. So we could use the result to complete the quantity codes with comment for each one. Guess that would help a lot to find the correct code without leaving the IDE.

**Comment by stephanstapel** [comment]
Yes, indeed.
You can find the diff here:

https://github.com/stephanstapel/OpenTrans.net/compare/4.0.2...master

I believed it was just too much so I took this as a reference:

https://github.com/stephanstapel/ZUGFeRD-csharp/blob/master/ZUGFeRD/QuantityCodes.cs

**Comment by jmu-horaios** [comment]
Ah, okay.
If you don't mind, I just created a pull request to extend the list of quantity codes. There are a lot for sure, but I don't see any harm in it, if they are half way organised.
