### ISSUE TITLE
24H format is not parsed.

### ISSUE THREAD

**Issue by liova99** [stephanstapel/OpenTrans.net#35]
Hi, thanks for the Lib. 

In the `BaseReader` Class there is the `_nodeAsDateTime()` method, which will return null if the time is in 24H format e.g. "2021-08-05T14:48:37"

To parse it you are using TryParseExact with the format "yyyy-MM-ddThh:mm:ss". the `hh` are for 12H for 24 one should use HH in C#.
Is that a bug or a requirement? :) 

Here the code https://github.com/stephanstapel/OpenTrans.net/blob/51cb41aeebe51ddafbb0c0a551d8ffce5807faf9/OpenTrans.net/BaseReader.cs#L51

I found that OpenTrans use  ISO 8601 (Second edition 1997) as the DateTime field, which is in 24H format
https://www.w3.org/TR/NOTE-datetime-970915

Should I make a PR replacing the format? 

Thanks again.

**Comment by stephanstapel** [comment]
Oops :) A PR would be more than great! Can you please add a test case for this?
