### ISSUE TITLE
date parsing ignores timezones

### ISSUE THREAD

**Issue by rainer-helbing** [stephanstapel/OpenTrans.net#38]
Hi Stephan,

while trying to load and store an ORDER_RESPONSE, I noticed that timezones are ignored.

The documentation says this:
![grafik](https://github.com/stephanstapel/OpenTrans.net/assets/39090978/b68e9d0f-9454-4d80-ab95-d77c03de5916)
 
But your code in BaseReader only reads the part before "+".

best regards
Rainer

**Comment by stephan-nowecor** [comment]
Hi @rainer-helbing 

thanks for reaching out. If you can issue a PR, I'd be more than happy.

**Comment by stephanstapel** [comment]
Hi @rainer-helbing

thanks for reaching out. If you can issue a PR, I'd be more than happy.

**Comment by stephanstapel** [comment]
like this:

https://github.com/stephanstapel/OpenTrans.net/commit/abf28279701da6a2d49c92007a90677a55db4ba8

?

**Comment by stephanstapel** [comment]
thinking about this:

![grafik](https://github.com/stephanstapel/OpenTrans.net/assets/2912080/78c9306e-f76a-4564-ab2a-3002ad3e1f9d)

Would you rather convert to local datetime, @rainer-helbing ?

**Comment by rainer-helbing** [comment]
Hi Stephan,

for the datetime - stuff, I shall send you a pull request

regards
Rainer
________________________________
Von: Stephan ***@***.***>
Gesendet: Samstag, 14. Oktober 2023 16:30
An: stephanstapel/OpenTrans.net ***@***.***>
Cc: Rainer Helbing ***@***.***>; Mention ***@***.***>
Betreff: Re: [stephanstapel/OpenTrans.net] date parsing ignores timezones (Issue #38)


thinking. Our would you rather convert to local datetime, @rainer-helbing<https://github.com/rainer-helbing> ?

**Comment by stephanstapel** [comment]
The code above is already in the master branch. Just update your fork.
