### ISSUE TITLE
Feature Request: Party.RolesUnknown

### ISSUE THREAD

**Issue by rainer-helbing** [stephanstapel/OpenTrans.net#39]
Hi Stephan,

I'm using your library to read an ORDER_RESPONSE, where the sender uses Parties with party roles that are not part of standard (e.g. "object_owner").
Fortunately your parser is able to read these values as `PartyRoles.unknown`.  However, I would like to know the original value, that was sent in the XML (i.e. "object_owner"). Therefore I would like to add an additional property to `Party`.
```csharp
        /// <summary>
        /// Original string values of each "unknown" party role 
        /// </summary>
        public List<string> RolesUnknown { get; set; } = new List<string>();
```
To load and store this property, `BaseReader` and `BaseWriter` would need to be modified.

If you agree to this new feature, I can send you a pull request for these changes. At the moment, I cannot push to your repository.

regards
Rainer

**Comment by stephanstapel** [comment]
Hi again,
you need to fork the repository, then you can commit to your fork and create pull request based on this.
I had a similar issue in the sister library and my only solution was this:

https://github.com/stephanstapel/BMECat.net/blob/master/BMECat.net/QuantityCode.cs

if you have a better idea, let me know. Otherwise, please follow this path.

**Comment by rainer-helbing** [comment]
Hi Stephan,

Changing the enum `PartyRoles` to a class like `QuantityCode` would be a breaking change in your library, which I would like to avoid. **Please let me know if you don't mind a breaking change**.

My solution adds the property `RolesUnknown` to `Party`. The new property holds the original values of all "unknown" party roles, that are in the `Roles` property.

### Example
XML snippet:
```xml
<PARTY>
  <PARTY_ROLE>buyer</PARTY_ROLE>
  <PARTY_ROLE>unknown-role-A</PARTY_ROLE>
  <PARTY_ROLE>unknown-role-B</PARTY_ROLE>
  <PARTY_ROLE>invoice_recipient</PARTY_ROLE>
...
</PARTY>
```
results to:
```csharp
  Roles = [Buyer, Unknown, Unknown, InvoiceRecipient];
  RolesUnknown = ["unknown-role-A","unknown-role-B"];
```
`BaseWriter` is able to construct the same XML again as long as values in `RolesUnknown`  are provided. If there are no or not enough values in `RolesUnknown` - the resulting XML value is as it is now: "unknown".

**Comment by stephanstapel** [comment]
closing with PR #40
