### ISSUE TITLE
Address Country

### ISSUE THREAD

**Issue by Schaussi** [stephanstapel/OpenTrans.net#5]
Hi Stephan,

it would be great if you could make some small adjustments regarding the Address item's country properties.
* "COUNTRY_CODE" should be "COUNTRY_CODE**D**"
* "COUNTRY" property as a separate string variable which can be set individually, like "Germany", "Deutschland", "Österreich", "Oesterreich", "Austria", etc.

Thank you!

**Comment by stephan-nowecor** [comment]
COUNTRY-CODED is fixed. Concerning the Country name, I prefer to leave it like that, using the official ISO country code to country name mapping (https://www.iso.org/obp/ui/#search)

**Comment by stephanstapel** [comment]
COUNTRY-CODED is fixed. Concerning the Country name, I prefer to leave it like that, using the official ISO country code to country name mapping (https://www.iso.org/obp/ui/#search)
